package com.xebia.xifire.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.xebia.xifire.model.EmployeeDetail;
import com.xebia.xifire.service.EmployeeDetailLocalServiceUtil;

/**
 * The extended model base implementation for the EmployeeDetail service. Represents a row in the &quot;employee_detail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDetailImpl
 * @see com.xebia.xifire.model.EmployeeDetail
 * @generated
 */
public abstract class EmployeeDetailBaseImpl extends EmployeeDetailModelImpl
    implements EmployeeDetail {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a employee detail model instance should use the {@link EmployeeDetail} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EmployeeDetailLocalServiceUtil.addEmployeeDetail(this);
        } else {
            EmployeeDetailLocalServiceUtil.updateEmployeeDetail(this);
        }
    }
}
