package com.xebia.xifire.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.xebia.xifire.model.ReimbursementItem;
import com.xebia.xifire.service.ReimbursementItemLocalServiceUtil;

/**
 * The extended model base implementation for the ReimbursementItem service. Represents a row in the &quot;reimbursement_item&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReimbursementItemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReimbursementItemImpl
 * @see com.xebia.xifire.model.ReimbursementItem
 * @generated
 */
public abstract class ReimbursementItemBaseImpl
    extends ReimbursementItemModelImpl implements ReimbursementItem {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a reimbursement item model instance should use the {@link ReimbursementItem} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ReimbursementItemLocalServiceUtil.addReimbursementItem(this);
        } else {
            ReimbursementItemLocalServiceUtil.updateReimbursementItem(this);
        }
    }
}
