package com.xebia.xifire.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.xebia.xifire.model.Salary;
import com.xebia.xifire.service.SalaryLocalServiceUtil;

/**
 * The extended model base implementation for the Salary service. Represents a row in the &quot;salary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SalaryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SalaryImpl
 * @see com.xebia.xifire.model.Salary
 * @generated
 */
public abstract class SalaryBaseImpl extends SalaryModelImpl implements Salary {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a salary model instance should use the {@link Salary} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SalaryLocalServiceUtil.addSalary(this);
        } else {
            SalaryLocalServiceUtil.updateSalary(this);
        }
    }
}
