package com.xebia.xifire.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.xebia.xifire.model.UserReimbursement;
import com.xebia.xifire.service.UserReimbursementLocalServiceUtil;

/**
 * The extended model base implementation for the UserReimbursement service. Represents a row in the &quot;user_reimbursement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserReimbursementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserReimbursementImpl
 * @see com.xebia.xifire.model.UserReimbursement
 * @generated
 */
public abstract class UserReimbursementBaseImpl
    extends UserReimbursementModelImpl implements UserReimbursement {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a user reimbursement model instance should use the {@link UserReimbursement} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            UserReimbursementLocalServiceUtil.addUserReimbursement(this);
        } else {
            UserReimbursementLocalServiceUtil.updateUserReimbursement(this);
        }
    }
}
