package com.xebia.xifire.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeDetail service. Represents a row in the &quot;employee_detail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.xebia.xifire.model.impl.EmployeeDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.xebia.xifire.model.impl.EmployeeDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDetail
 * @see com.xebia.xifire.model.impl.EmployeeDetailImpl
 * @see com.xebia.xifire.model.impl.EmployeeDetailModelImpl
 * @generated
 */
public interface EmployeeDetailModel extends BaseModel<EmployeeDetail> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee detail model instance should use the {@link EmployeeDetail} interface instead.
     */

    /**
     * Returns the primary key of this employee detail.
     *
     * @return the primary key of this employee detail
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee detail.
     *
     * @param primaryKey the primary key of this employee detail
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this employee detail.
     *
     * @return the ID of this employee detail
     */
    public long getId();

    /**
     * Sets the ID of this employee detail.
     *
     * @param id the ID of this employee detail
     */
    public void setId(long id);

    /**
     * Returns the user ID of this employee detail.
     *
     * @return the user ID of this employee detail
     */
    public long getUserId();

    /**
     * Sets the user ID of this employee detail.
     *
     * @param userId the user ID of this employee detail
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this employee detail.
     *
     * @return the user uuid of this employee detail
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this employee detail.
     *
     * @param userUuid the user uuid of this employee detail
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the employee code of this employee detail.
     *
     * @return the employee code of this employee detail
     */
    @AutoEscape
    public String getEmployeeCode();

    /**
     * Sets the employee code of this employee detail.
     *
     * @param employeeCode the employee code of this employee detail
     */
    public void setEmployeeCode(String employeeCode);

    /**
     * Returns the designation of this employee detail.
     *
     * @return the designation of this employee detail
     */
    @AutoEscape
    public String getDesignation();

    /**
     * Sets the designation of this employee detail.
     *
     * @param designation the designation of this employee detail
     */
    public void setDesignation(String designation);

    /**
     * Returns the location of this employee detail.
     *
     * @return the location of this employee detail
     */
    @AutoEscape
    public String getLocation();

    /**
     * Sets the location of this employee detail.
     *
     * @param location the location of this employee detail
     */
    public void setLocation(String location);

    /**
     * Returns the department of this employee detail.
     *
     * @return the department of this employee detail
     */
    @AutoEscape
    public String getDepartment();

    /**
     * Sets the department of this employee detail.
     *
     * @param department the department of this employee detail
     */
    public void setDepartment(String department);

    /**
     * Returns the pf number of this employee detail.
     *
     * @return the pf number of this employee detail
     */
    @AutoEscape
    public String getPfNumber();

    /**
     * Sets the pf number of this employee detail.
     *
     * @param pfNumber the pf number of this employee detail
     */
    public void setPfNumber(String pfNumber);

    /**
     * Returns the doj of this employee detail.
     *
     * @return the doj of this employee detail
     */
    public Date getDoj();

    /**
     * Sets the doj of this employee detail.
     *
     * @param doj the doj of this employee detail
     */
    public void setDoj(Date doj);

    /**
     * Returns the bank account of this employee detail.
     *
     * @return the bank account of this employee detail
     */
    @AutoEscape
    public String getBankAccount();

    /**
     * Sets the bank account of this employee detail.
     *
     * @param bankAccount the bank account of this employee detail
     */
    public void setBankAccount(String bankAccount);

    /**
     * Returns the pan number of this employee detail.
     *
     * @return the pan number of this employee detail
     */
    @AutoEscape
    public String getPanNumber();

    /**
     * Sets the pan number of this employee detail.
     *
     * @param panNumber the pan number of this employee detail
     */
    public void setPanNumber(String panNumber);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EmployeeDetail employeeDetail);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EmployeeDetail> toCacheModel();

    @Override
    public EmployeeDetail toEscapedModel();

    @Override
    public EmployeeDetail toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
