package com.xebia.xifire.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserReimbursement service. Represents a row in the &quot;user_reimbursement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.xebia.xifire.model.impl.UserReimbursementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.xebia.xifire.model.impl.UserReimbursementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserReimbursement
 * @see com.xebia.xifire.model.impl.UserReimbursementImpl
 * @see com.xebia.xifire.model.impl.UserReimbursementModelImpl
 * @generated
 */
public interface UserReimbursementModel extends BaseModel<UserReimbursement> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a user reimbursement model instance should use the {@link UserReimbursement} interface instead.
     */

    /**
     * Returns the primary key of this user reimbursement.
     *
     * @return the primary key of this user reimbursement
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this user reimbursement.
     *
     * @param primaryKey the primary key of this user reimbursement
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the ID of this user reimbursement.
     *
     * @return the ID of this user reimbursement
     */
    public int getId();

    /**
     * Sets the ID of this user reimbursement.
     *
     * @param id the ID of this user reimbursement
     */
    public void setId(int id);

    /**
     * Returns the create date of this user reimbursement.
     *
     * @return the create date of this user reimbursement
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this user reimbursement.
     *
     * @param createDate the create date of this user reimbursement
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this user reimbursement.
     *
     * @return the modified date of this user reimbursement
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this user reimbursement.
     *
     * @param modifiedDate the modified date of this user reimbursement
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the user ID of this user reimbursement.
     *
     * @return the user ID of this user reimbursement
     */
    public int getUserId();

    /**
     * Sets the user ID of this user reimbursement.
     *
     * @param userId the user ID of this user reimbursement
     */
    public void setUserId(int userId);

    /**
     * Returns the description of this user reimbursement.
     *
     * @return the description of this user reimbursement
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this user reimbursement.
     *
     * @param description the description of this user reimbursement
     */
    public void setDescription(String description);

    /**
     * Returns the status of this user reimbursement.
     *
     * @return the status of this user reimbursement
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this user reimbursement.
     *
     * @param status the status of this user reimbursement
     */
    public void setStatus(String status);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(UserReimbursement userReimbursement);

    @Override
    public int hashCode();

    @Override
    public CacheModel<UserReimbursement> toCacheModel();

    @Override
    public UserReimbursement toEscapedModel();

    @Override
    public UserReimbursement toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
